services:
  db:
    image: postgres:17
    container_name: tko_database
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: x6b6nNaOQK0Iy-J
      POSTGRES_DB: tko_database
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tko_database
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: x6b6nNaOQK0Iy-J
    depends_on:
      - db
    volumes:
      - ./src/main/media:/app/media
      - ./src/main/resources/peopleSVG:/app/svg
volumes:
  pgdata: